apiVersion: v2
name: tigertail
description: A Helm chart for Tiger-Tail Microblog
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: "~12.5.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "~17.11.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
