apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tigertail.fullname" . }}-credentials
  labels:
    {{- include "tigertail.labels" . | nindent 4 }}
type: Opaque
data:
  db-user: {{ .Values.config.database.user | b64enc | quote }}
  db-password: {{ .Values.config.database.password | b64enc | quote }}
  redis-password: {{ .Values.config.cache.password | b64enc | quote }}
  auth-username: {{ .Values.config.auth.username | b64enc | quote }}
  auth-password: {{ .Values.config.auth.password | b64enc | quote }}
