apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tiger-tail-chart.fullname" . }}-secrets
  labels:
    {{- include "tiger-tail-chart.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64-encoded secret data
  db-user: {{ .Values.secrets.dbUser | b64enc | quote }}
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}
  db-name: {{ .Values.secrets.dbName | b64enc | quote }}
  auth-username: {{ .Values.secrets.authUsername | b64enc | quote }}
  auth-password: {{ .Values.secrets.authPassword | b64enc | quote }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc | quote }}
